import test from 'node:test';import assert from 'node:assert/strict';import {musicUrl,matchedSong,safeImage} from '../site/music.js';import fs from 'node:fs';
const sp='https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC';const ap='https://music.apple.com/us/album/test/123?i=456';
test('Canonical Spotify and Apple tracks',()=>{assert.equal(musicUrl(sp+'?si=x'),sp);assert.equal(musicUrl(sp.replace('/track/','/intl-de/track/')),sp);assert.equal(musicUrl(ap+'&uo=4'),ap);assert.ok(musicUrl('https://music.apple.com/us/song/test/456'));});
test('Reject executable, lookalike, credential, album, playlist and wrong-service URLs',()=>{for(const u of ['javascript:alert(1)','http://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC',sp.replace('open.spotify.com','open.spotify.com.evil.com'),sp.replace('https://','https://name@'),sp.replace('/track/','/playlist/'),'https://music.apple.com/us/album/test/123',sp.replace('.com/','.com:8443/')])assert.equal(musicUrl(u),null,u);assert.equal(musicUrl(ap,'spotify'),null);assert.equal(safeImage('javascript:alert(1)'),null);});
test('Map MusicLink responses and preserve the pasted source',()=>{const data={success:true,data:[{type:'track',title:'Test',artist:'Artist',image_url:'https://example.com/a.jpg',platforms:{apple_music:ap}}]};assert.deepEqual(matchedSong(data,sp),{title:'Test',artist:'Artist',artwork_url:'https://example.com/a.jpg',spotify_url:sp,apple_url:ap});data.data[0].type='album';assert.throws(()=>matchedSong(data,sp),/song link/);});
test('Normalize countryless and short Apple Music links for database storage',()=>{assert.equal(musicUrl('https://music.apple.com/song/456'),'https://music.apple.com/us/song/track/456');assert.equal(musicUrl('https://music.apple.com/gb/song/456'),'https://music.apple.com/gb/song/track/456');assert.equal(musicUrl('https://music.apple.com/album/test/123?i=456'),ap);assert.equal(musicUrl('https://music.apple.com/album/test/123'),null);});
test('Choose the source recording across multiple matches and reject unsafe links',()=>{const data={success:true,data:[{type:'track',title:'Other recording',platforms:{}},{type:'track',title:'Correct',artist:'Artist',platforms:{spotify:sp,apple_music:'https://music.apple.com/song/456'},image_url:'javascript:alert(1)'}]};assert.deepEqual(matchedSong(data,sp),{title:'Correct',artist:'Artist',artwork_url:null,spotify_url:sp,apple_url:'https://music.apple.com/us/song/track/456'});data.data[1].platforms.apple_music='https://evil.example/song/456';assert.equal(matchedSong(data,sp).apple_url,null);assert.throws(()=>matchedSong({success:false,error:'secret provider detail'},sp),/No matching song/);assert.throws(()=>matchedSong({success:true,data:[]},sp),/song link/);});
test('Apple Music input finds Spotify and retains its original storefront',()=>{const data={success:true,data:[{type:'track',title:'Test',artist:'Artist',platforms:{spotify:sp,apple_music:'https://music.apple.com/song/456'}}]};assert.equal(matchedSong(data,ap).spotify_url,sp);assert.equal(matchedSong(data,ap).apple_url,ap);});
test('Browser and server validation stay identical',()=>assert.equal(fs.readFileSync(new URL('../site/music.js',import.meta.url),'utf8'),fs.readFileSync(new URL('../supabase/functions/song-api/music.js',import.meta.url),'utf8')));
